# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: NoMulti
main: com.github.Invicter.NoMulti
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: 2.2
website: http://dev.bukkit.org/server-mods/nomulti
description: Easy, and lightweight multi account (per IP) blocker
author: Invicter
commands:
  nomulti:
    description: In game acces to NoMulti plugin
    usage: /nomulti exception add <nickName> - Adds a new player exception
           /nomulti exception remove <nickName> - Removes player exception
           /nomulti remove <IP> - Removes IP from database
           /nomulti add <IP> <nickName> - Adds new IP to player binding
           /nomulti reload - Reloads plugin